#! /bin/bash

# why in the world do i have this when i have rake tasks for this?
#
# because it's a lot easier to whip up a quick bash script for this 
# than to have to write bash in ruby

rm -rf doc
rm -rf pkg

echo "creating gem ... be sure to check/update the Manifest.txt!"

# update version revision
REVISION="$(git log --pretty=oneline | wc -l)"
cat lib/snips/version.rb | sed "s/SCM = \(.*\)/SCM = $REVISION/g" > "tmp/version_$REVISION.rb"
cp "tmp/version_$REVISION.rb" lib/snips/version.rb

rake docs
rake package

echo -e "\n\ndone!"
